### ISSUE TITLE
Clarify the targeted software

### ISSUE THREAD

**Issue by sa7mon** [freenas/iocage-plugin-btsync#1]
Is this repo for BTSync/Resilio Sync or for SyncThing? The nginx config seems to be for proxy-pass'ing SyncThing which AFAIK is a completely different package.

**Comment by MiwiDots** [comment]
Hi, 

Sorry for the late respond. You are right it looks wrong. It is suppose to link to resilio, I will fix that in a while.

**Comment by MiwiDots** [comment]
Fixed thank you.
